apiVersion: apps/v1
kind: Deployment
metadata:
    name: dotnetapp
    namespace: dotnet-app
spec:
    replicas: 2

    selector:
        matchLabels:
            app: dotnet-app
    template:
        metadata:
            labels:
                app: dotnet-app
        spec:
            containers:
            - name: dotnet-app
              image: 000418617326.dkr.ecr.us-east-1.amazonaws.com/dotnet_repo:latest
              ports:
              - containerPort: 8080
